### ISSUE TITLE
Navigation overrides lightbox at top of page

### ISSUE THREAD

**Issue by adamish717** [adamish717/canary-site#1]
On the Guides page, if you click the brochure "View types of folds" and look at the lightbox, it fights with the navigation for some reason

**Comment by adamish717** [comment]
Fixed with https://github.com/adamish717/canary-site/commit/441c2f3bd2bbb4b45d802d3ff31855210b413f19

**Comment by Sinetheta** [comment]
Try to make the link between issues and commits int he commit message. Eg: "Fixes #1" and this issue will close automagically.
