### ISSUE TITLE
Product page icons are confusing

### ISSUE THREAD

**Issue by Sinetheta** [adamish717/canary-site#8]
Is it just me who finds these super distracting an almost completely unrelated to their bullet points?

![screen shot 2015-05-12 at 10 30 24 pm](https://cloud.githubusercontent.com/assets/1529452/7604371/8a708aa4-f8f6-11e4-9c50-17a319f19773.png)

_Quick_ what are those icons describing?

**Comment by adamish717** [comment]
Fixing the "quantity" icon to better represent quantity.

The cog icons represent the additional 'work' for the finishes on the products.  The difficult was finding two similar icons for "finishes" and "additional finishes".

If you have a better option for those two, please submit a PR

**Comment by Sinetheta** [comment]
I'm suggesting you rethink the layout here. At best I feel that these icons are not adding value. At worst I think they're creating confusion on the page.
